
language: ruby

rvm:
  - 2.2.2

notifications:
  email: false

addons:
  postgresql: 9.4

before_script:

  # Enable PostGIS.
  - psql -U postgres -c "CREATE EXTENSION POSTGIS"

  # Create database, apply Travis config.
  - psql -c "CREATE DATABASE graves_test;" -U postgres
  - psql -c "CREATE DATABASE graves_legacy;" -U postgres
  - cp config/database.yml.travis config/database.yml

  # Load the schema.
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare

  # Build static payloads.
  - npm install -g npm@3.7.5
  - npm install -g grunt-cli
  - npm install

script:

  - bundle exec rake
  - grunt compile:min
  - grunt jasmine
